name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Setting up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
